---
repository:
  name: gettext_i18n_rails_js
  description: Extends gettext_i18n_rails making your .PO files available to client side javascript as JSON
  homepage: https://github.com/webhippie/gettext_i18n_rails_js
  topics: ruby, rubygem, gettext, i18n, rails

  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        users: []
        teams: []

...
